### PR TITLE
Fixed the .desktop file category

### PR DESCRIPTION
**Pull request by Mailaender**
See https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories#Settings

### CODE REVIEW

**Comment by kozec** [comment]
SUSE uses other category names as other distros, so this is patched on-the-fly in OBS. [Freedesktop defines](https://standards.freedesktop.org/menu-spec/latest/apa.html) only Game and Settings and I don't think that SCC fits into Settings as it's full-fledged application.

**Comment by Mailaender** [comment]
> SUSE uses other category names as other distros

Actually SUSE just enforces the FreeDesktop standard (rather strictly). The second category is also compliant with https://standards.freedesktop.org/menu-spec/latest/apas02.html

> I don't think that SCC fits into Settings as it's full-fledged application.

It is a category for applications that configure something just like http://roccat.sourceforge.net/ which also uses this category. Certainly it is not a game.

**Comment by kozec** [comment]
> It is a category for applications that configure something just like http://roccat.sourceforge.net/ which also uses this category. Certainly it is not a game.

But you need to start it every time, so it's not control panel :)

Main problem here is that moving it to Setting category doesn't work on any of my installations - SCC is not displayed anywhere. But if OpenSUSE has no problem with that, I can "merge" it into path in OBS, so OpenSUSE (or possibly all RPM) packages are going to be built with correct categories.

**Comment by Mailaender** [comment]
> Main problem here is that moving it to Setting category doesn't work on any of my installations 

Which desktops or distributions cause such problems?

> I can "merge" it into patch in OBS, so OpenSUSE (or possibly all RPM) packages

Either take it or reject it. Also the category itself isn't set in stone. I just want to fix the visual inconsistency for desktops with traditional menus such as KDE or Cinnamon and fix the `rpmlint` error to get my package accepted in @openSUSE. See https://build.opensuse.org/request/show/452030 for my submission which is based on a heavily cleaned up version of your .spec file.

**Comment by kozec** [comment]
Ok, you convinced me :)

I'm using XFCE, but problem was most likely in some cache, as SCC is now shown in Settings group. In worst case, I'll revert it back if it breaks for anyone else.

**Comment by Mailaender** [comment]
Sounds like a packaging problem as `update-desktop-database` should be called after the installation. See https://en.opensuse.org/openSUSE:Packaging_Conventions_RPM_Macros#.25desktop_database_post_.2F_.25desktop_database_postun

**Pull request merged**
