### PR TITLE
Update README.md to reflect new Void Linux package

### PR DESCRIPTION
**Pull request by KeepBotting**
Simple change to README, there is now a `sc-controller` package in Void's repository.

### CODE REVIEW

**Comment by Vintodrimmer** [comment]
I'm not sure you should add it yet.

The last version is currently 0.3.16, since we have no `python-evdev` in repos, which is required for versions 0.4.0+ and I don't know how to implement it without making the package.

**Comment by kozec** [comment]
> The last version is currently 0.3.16, since we have no python-evdev in repos, which is required for versions 0.4.0+ and I don't know how to implement it without making the package.

Next version will be able to run without python-evdev, although it's not ideal. If it helps, I can make new release as it is, commits since 0.4.0.1 are just really small fixes.

There is also possible to bundle python-evdev as AppImage version did, but that's probably not usable for package.

**Comment by Vintodrimmer** [comment]
That would help, thanks!

If `sc-controller` is able to work without it I'll update the package and then add `python-evdev` when I figure out a way to do that. Maybe I'll make a package after all.

**Comment by kozec** [comment]
> If sc-controller is able to work without it I'll update the package and then add python-evdev when I figure out a way to do that. Maybe I'll make a package after all.

Ok, no problem, but just to be clear, support for non-steam controllers is not going to work without that package.

**Comment by Vintodrimmer** [comment]
@kozec Got it.

Luckily, @maxice8 has made a [package](https://github.com/voidlinux/void-packages/pull/10533) already, so it's only a matter of time now.

**Comment by maxice8** [comment]
@Vintodrimmer python-evdev has been merged into void-packages https://github.com/voidlinux/void-packages/commit/3a92b6bb973b14e8ef66ab283ab919c23f5ad060

**Comment by Vintodrimmer** [comment]
I did screw up a bit with the commit name, but have compiled the package and it seems to be working (at least with Steam Controller). So I made a PR and it should be updated sooner or later.

So yeah, I think it's safe to update the readme.

**Comment by maxice8** [comment]
On Mon, Jan 08, 2018 at 01:59:56PM -0800, Vintodrimmer wrote:
> I did screw up a bit with the commit name, but have compiled the package and it seems to be working (at least with Steam Controller). So I made a PR and it should be updated sooner or later.
> 
> So yeah, I think it's safe to update the readme.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kozec/sc-controller/pull/305#issuecomment-356110127

commits can be renamed with `git --amend`

**Comment by Vintodrimmer** [comment]
I was sure that it works only for the unpublished files.

Thank you once again!

**Comment by kozec** [comment]
Ok, merged. Thanks :)

**Pull request merged**
