### PR TITLE
[FEATURE] Implements Hip fire style action for trigger

### LINKED ISSUE #187: Hip fire trigger style
In Steam the triggers have different trigger styles I especially miss the hip fire exclusive mode which allows me to exclusively trigger the soft binding or the full binding but the other hip fire variants are nice to have as well...

### PR DESCRIPTION
**Pull request by ren2r**
Closes #187 

Implements Hip fire style trigger using two ranges for two different actions allowing activating the fully pressed action without activating partially pressed one.
It differs from the current possibilitie because allow pressing the fully pressed action without activating the partially pressed.
Example:
Using current method, settings two actions on trigger will result in something like this:

> trigger(50, 255, button(Keys.KEY_S)) and trigger(254, 255, button(Keys.KEY_F))

This activate the Key_S while the trigger is in range from 50 to 255, and activate Key_F when the trigger reach the range 254 to 255, in this range it will keep active the two actions.
Setting the release the partially pressed action when fully press will result in action like this:

> trigger(50, 254, button(Keys.KEY_S)) and trigger(254, 255, button(Keys.KEY_F))

This is similar to the previous, but the partially pressed action will execute in the range 50 to 254, and will release when fully pressed the trigger.

This pull request implements a new action as the example bellow:

> hipfire(50, 254, button(Keys.KEY_S), button(Keys.KEY_F), NORMAL,0.1)

Where is set, in this order:
>
* the partially pressed level,
* the fully pressed level,
* partially pressed action,
* fully pressed action,
* mode of operation [NORMAL, EXCLUSIVE, SENSIBLE],
* delay before activate the partially pressed action
>
It works as follows:

When pressing the trigger and reach the partially pressed action it will start a timer, if you press the trigger fully before the timer runs out, it will activate the fully pressed action without activating the partially pressed, otherwise it will activate the partially pressed on the time out or if you release the trigger. But if you reach the fully pressed action before the timeout, it will not activate the partially pressed action before releasing the trigger again.

### CODE REVIEW

**Comment by ren2r** [comment]
More clarification about the pull request.
The problem this pull request try to fix is the following:
I wanted to set two actions in my trigger, in partially pressed and another in fully pressed, but in some times I want to press the fully press action without activating the partially press action.
For example:
In a shooter, I map the partially pressed to RIGHT_MOUSE (aim down sights) and the fully pressed to LEFT_MOUSE (shoot). In some situation I want to aim before shoot, so I just press gently the trigger and wait the aim appear, and then I press the trigger fully to shoot. This works great, but some times I want to just shoot very quickly without aiming, but the current way will not work because the partially pressed action will execute. Even using a hold modifier in partially press will not work in many cases, I will trigger the fully pressed action first, but after the delay times out it will trigger the partially pressed action too.

So, this implementation is just basic and aim to allow situations when you would want to press the fully pressed action without the risk of activating the partially pressed action.

**Comment by ren2r** [comment]
I've made a little change to the Trigger Action Editor too, to accommodate the hipfire options, but it was just a basic suggestion.

**Comment by kozec** [comment]
Thanks, this looks great. I'm testing it right now and I finally get what's the difference. Does [WIP] in the title mean you are still working on some changes?

**Comment by ren2r** [comment]
Yes I refereced as wip because I was not sure if you would like change something or integrate in the UI in another place... 
there is still the "timeout" property that I did not integrate in the UI becasue was afraid of poluting the UI too much
And theres a little thing that I am experiencing. when I press the trigger the fully pressed action is activated before the click when you have just turned on the controller, as like it has not been calibrated yet. I tought about adding the conditional `mapper.is_pressed(SCButtons.RT)` if the fully pressed range start in 254, but was not sure if it is the better aproach.
I have this same issue with the trigger action like this:

> trigger(254, 255, button(Keys.BTN_RIGHT)) 

that is activated before the click if the controller has not been calibrated yet.

**Comment by ren2r** [comment]
I guess the implementation is complete.
If you found some issue on your tests or would like to change something, just tell.
I guess the docs should be updated too if this gets merged, but I'm waiting a confirmation before changing something else.

**Comment by kozec** [comment]
Looks good for me. I was not able to break it in any way :)

**Comment by ren2r** [comment]
I've just pushed the addition of the hipfire action into the Documentation.
I do not speak english very well (problably the opposite), so it might not be too clear, but I guess it's everything in there.

**Comment by kozec** [comment]
Sounds okay to me, but then, I'm not native speaker either. Thank you very much for your help :)

**Pull request merged**
