### PR TITLE
Implement best match gesture lookup

### PR DESCRIPTION
**Pull request by DarkArc**
This very similar to my original proposal in https://github.com/kozec/sc-controller/issues/380. 

Using python's difflib, this finds the closest resembled gesture, and executes it, if exact match and ignored stroke match, fail to find a result.

This will pick the best of all matches with more than 50% equivalence. In my testing this made gestures far more enjoyable to use. :)

Might also be neat if `MINIMUM_MATCH_RATIO` could be exposed and made configurable as well, but this is a start; wanted to get feedback.

### CODE REVIEW

**Comment by kozec** [comment]
Whoa, that looks surprisingly simple.

> Might also be neat if MINIMUM_MATCH_RATIO could be exposed and made configurable as well, but this is a start; wanted to get feedback.

It could be done by adding ratio as first, optional parameter to gestures(). Basically, if first item in `stuff` [here](https://github.com/kozec/sc-controller/pull/382/files#diff-9b00d10efb30e428211aa1181284eb0dR618) is number, it's value for MINIMUM_MATCH_RATIO. And I can add slider that configures it in GUI.

**Comment by DarkArc** [comment]
> Whoa, that looks surprisingly simple.
Haha yeah, the existence of `difflib` made it a lot easier



>>Might also be neat if MINIMUM_MATCH_RATIO could be exposed and made configurable as well, but this is a start; wanted to get feedback.

>It could be done by adding ratio as first, optional parameter to gestures(). Basically, if first item in stuff here is number, it's value for MINIMUM_MATCH_RATIO. And I can add slider that configures it in GUI.

Okay cool, I might take a stab at that when I get a chance

----

I'm also wondering, do we need the ignore stroke length settings with this? I feel like the problems that would try to solve would also be fixed by this.

**Comment by kozec** [comment]
> I'm also wondering, do we need the ignore stroke length settings with this? I feel like the problems that would try to solve would also be fixed by this.

Yes, for backwards compatibility if for nothing else.

**Comment by kozec** [comment]
@DarkArc From our communication I was under impression you are planning to modify this PR. Or can I merge it as it is? If that's the case, I will probably add that MINIMUM_MATCH_RATIO option as I described above.

**Comment by kozec** [comment]
Ok, merged along with slider in GUI.

**Pull request merged**
