### PR TITLE
Update README to include Exherbo package

### PR DESCRIPTION
**Pull request by tgurr**
I've created an exheres for Exherbo Linux living in our ::hardware repository, allowing to easily install sc-controller via our package manager.

### CODE REVIEW

**Comment by kozec** [comment]
Thanks :+1:

**Comment by kozec** [comment]
Just as unrelated side-note, that linked page is kinda broken...

delme

**Comment by tgurr** [comment]
The site uses a certificate from CAcert.org which most distributions include the root ca for, including ours, so I didn't notice that problem myself, thanks for the hint! Maybe it's time to just switch to Let's Encrypt, I'll have to ask our infra guys about that.

**Comment by kozec** [comment]
Ah, sure, you are right, it works on Linux machine. That's what I get from accepting PRs from lesser OSes :)

**Pull request merged**
