### PR TITLE
profile for DiRT Rally with gyro steering

### PR DESCRIPTION
**Pull request by predr**
Mentioned in the issue #253.

### CODE REVIEW

**Comment by kozec** [comment]
Thanks :)

**Comment by predr** [comment]
No no no... thank you :)

I was wondering, would it be possible to emulate a generic wheel? Is 1:1 movement of gyro to wheel in game possible? Racing games tend to slow down stick movement because they expect less precise movement. This profile emulates stick so it suffers a bit from that "optimization".

**Comment by kozec** [comment]
In theory, yes, tou can change what kind of device SCC pretends to be, but only by editting `~/.confgi/scc/config.yml`. But I'm not sure if there is any game with support for wheels...

**Comment by predr** [comment]
I'm guessing you meant 'output' in config.json. Ok, thanks for the info.
http://support.feralinteractive.com/en/mac-linux-games/dirtrally/faqs/wheels_linux/

**Pull request merged**
