### PR TITLE
colors and style reloaded

### PR DESCRIPTION
**Pull request by predr**
Made these changes for your consideration. Minimal barely transparent menus and keyboard so it looks nice over game and is still clearly visible. Better looking messages.

Used black and white colors so that text and highlight colors can be changed from green to blue, red etc. to represent different controllers if needed later.

There is a config option for opacity but it is not read from there. If you don't mind you do configuration part. There should be option to disable opacity if users are having performance issues.

### CODE REVIEW

**Comment by kozec** [comment]
That looks pretty good, maybe just that message box should have at least little border all around.

But more importantly, are you saying you managed to get transparency working? That's great...

**Comment by predr** [comment]
I would prefer it without border, for me that is the idea behind transparency - blend into games. I don't think dark games are problem because menu and keyboard will still be clearly visible just not where they begin/end. + minimal design means getting rid of everything but essential information... but it's your choice just let me know if you still want it.

I'm on Ubuntu 16.04. Transparency is on entire window and minimal only 5%. Using background: transparent to make just backgrounds transparent didn't work.

**Comment by predr** [comment]
This also works.

**Comment by kozec** [comment]
Well, I can always leave border configurable, IRRC it shows differently on Ubuntu anyway.

That last picture looks good as well. I'll try to check out your branch, add config UI and merge everything to master if you are OK with that :)

**Comment by predr** [comment]
Awesome, I'll start working on something else. :)

**Comment by kozec** [comment]
It may looks like I forgot about this, but in fact, I just merged it into v0.4 branch, along with long needed GUI for selecting color scheme and style.

styles

I just wanna check, is it OK with you to call this style "Reloaded", or it was meant just for PR title? :)

**Comment by predr** [comment]
Nice! Yeah ok, sounds good.

**Pull request closed without merging**
