### PR TITLE
Ui spacing

### PR DESCRIPTION
**Pull request by dyskette**
These are changes to the simple dialogs that rename/create/view profiles details and the spacing on the main UI.

How it looks: https://youtu.be/DshJzkm8YXA

### CODE REVIEW

**Comment by kozec** [comment]
Nice, that looks great. But can you, please, fix that missing ID travis is complaining about? Ubuntu tends to throw error when glade with missing IDs is loaded.

```
AssertionError: Widget has no ID in glade/app.glade; class GtkHeaderBar; Parent id: dlgProfileDetails
```

**Comment by kozec** [comment]
Hey, I've probably edited my post after you saw it, sorry about that.

I've noticed that you replaced close buttons with "Cancel" buttons on some dialogs. I don't think that's a good idea; First, it is not consistent with everything else, and 2nd, those "Cancel" buttons are drawn on other side of window as "X" button is.

**Comment by dyskette** [comment]
Yeah, I didn't see the edit.

Consistency, that makes sense. I will see to it this monday I think because I'm away from my PC this weekend.

BTW, there is lots of trailing whitespace in the python files. I only noticed because `git am` complained about it. I just wanted to mention it.

**Comment by dyskette** [comment]
This is how the dialogs look now:

captura de pantalla de 2018-03-15 06-05-19

**Comment by kozec** [comment]
Great :) Thanks!

**Pull request merged**
